from .core import (
    extract_text_from_pdf,
    extract_texts_from_pdfs,
    extract_text,
    extract_texts,
    chunk_document,
    chunk_documents,
    embed_chunks,
    embed_documents,
    get_document_embedding,
    document_similarity_matrix,
    chunk_similarity_matrix,
    flag_plagiarism,
    find_most_similar_chunks,
    PLAGIARISM_THRESHOLD,
    build_index,
    search_similar_chunks,
    find_plagiarised_chunks,
    save_index,
    load_index,
    ChunkRecord,
    build_index_from_matrix,
    translate_text,
)
from .db import (
    init_db,
    verify_user,
    get_user_role,
    get_all_users,
    add_user,
    delete_user,
    update_password,
    init_corpus_db,
    add_document,
    get_document_by_hash,
    get_all_documents,
    add_chunks,
    get_chunk_registry,
    get_all_embeddings,
    delete_document,
    clear_all_data,
    get_document_chunks_count,
)
from .visualization import (
    plot_similarity_heatmap,
    plot_similarity_heatmap_plotly,
    plot_chunk_similarity_comparison,
    plot_similarity_network,
)

__all__ = [
    "extract_text_from_pdf", "extract_texts_from_pdfs",
    "extract_text", "extract_texts",
    "chunk_document", "chunk_documents",
    "embed_chunks", "embed_documents", "get_document_embedding",
    "document_similarity_matrix", "chunk_similarity_matrix",
    "flag_plagiarism", "find_most_similar_chunks", "PLAGIARISM_THRESHOLD",
    "plot_similarity_heatmap", "plot_similarity_heatmap_plotly",
    "plot_chunk_similarity_comparison", "plot_similarity_network", "translate_text",
    "build_index", "search_similar_chunks", "find_plagiarised_chunks",
    "save_index", "load_index", "ChunkRecord", "build_index_from_matrix",
    "init_db", "verify_user", "get_user_role", "get_all_users", "add_user", "delete_user", "update_password",
    "init_corpus_db", "add_document", "get_document_by_hash",
    "get_all_documents", "add_chunks", "get_chunk_registry",
    "get_all_embeddings", "delete_document", "clear_all_data", "get_document_chunks_count",
]
